# Generated by Django 4.2 on 2024-11-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_categoty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
